name: TestCI

on: 
  push:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          xcodebuild clean build -project TestCI.xcodeproj -scheme TestCI -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project TestCI.xcodeproj -scheme TestCITests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
